In [11]:
import numpy as np
import pandas as pd
import csv

ds = pd.read_csv("new.csv") #loads the csv correctly
ds

,Date,freeport,size,total,Total No. Cascade,protested,gsr encoding,weights
0,1/01/2017,1,1.0,1.0,1.0,0,0,0
1,4/01/2017,1,1.0,1.0,1.0,0,0,0
2,5/01/2017,24,11.0,6.0,24.0,0,0,0
3,6/01/2017,32,11.0,11.0,32.0,0,0,0
4,7/01/2017,2,1.0,2.0,2.0,0,0,0
5,8/01/2017,1,1.0,1.0,1.0,0,1,100
6,9/01/2017,20,12.0,8.0,20.0,0,0,0
7,10/01/2017,22,10.0,3.0,12.0,0,0,0
8,11/01/2017,8,6.0,2.0,8.0,0,0,0
9,12/01/2017,6,1.0,5.0,5.0,0,0,0
10,13/01/2017,39,10.0,18.0,29.0,0,0,0
11,14/01/2017,27,11.0,6.0,16.0,0,0,0
12,16/01/2017,1,1.0,1.0,1.0,0,1,100
13,17/01/2017,10,4.0,7.0,10.0,0,1,100
14,18/01/2017,5,2.0,2.0,3.0,0,0,0
15,19/01/2017,3,1.0,3.0,3.0,0,0,0
16,20/01/2017,2,1.0,2.0,2.0,0,0,0
17,21/01/2017,5,1.0,5.0,5.0,0,2,200
18,22/01/2017,14,5.0,7.0,13.0,0,0,0
19,23/01/2017,12,4.0,7.0,12.0,0,0,0
20,24/01/2017,3,1.0,3.0,3.0,0,2,200
21,26/01/2017,5,1.0,4.0,4.0,0,0,0
22,27/01/2017,17,7.0,6.0,14.0,0,0,0
23,28/01/2017,12,NaN,NaN,NaN,0,0,0
24,29/01/2017,7,3.0,2.0,4.0,0,0,0
25,30/01/2017,5,1.0,5.0,5.0,0,0,0
26,31/01/2017,5,1.0,5.0,5.0,0,0,0
27,1/02/2017,4,2.0,3.0,4.0,0,0,0
28,2/02/2017,4,1.0,4.0,4.0,0,0,0
29,3/02/2017,4,2.0,3.0,4.0,0,1,100
...,...,...,...,...,...,...,...,...
80,1/04/2017,45,13.0,10.0,43.0,0,0,0
81,2/04/2017,28,9.0,9.0,26.0,0,0,0
82,3/04/2017,11,2.0,7.0,9.0,0,0,0
83,4/04/2017,47,7.0,29.0,43.0,0,0,0
84,5/04/2017,29,3.0,23.0,25.0,0,0,0
85,6/04/2017,55,7.0,39.0,52.0,0,0,0
86,7/04/2017,46,5.0,22.0,41.0,0,1,100
87,8/04/2017,25,14.0,6.0,21.0,0,0,0
88,9/04/2017,23,12.0,6.0,20.0,0,0,0
89,10/04/2017,16,4.0,5.0,11.0,0,0,0
90,11/04/2017,21,3.0,11.0,17.0,0,0,0
91,12/04/2017,12,3.0,7.0,10.0,0,0,0
92,13/04/2017,15,2.0,10.0,13.0,0,0,0
93,14/04/2017,14,2.0,6.0,8.0,0,0,0
94,15/04/2017,4,1.0,2.0,2.0,0,0,0
95,16/04/2017,9,7.0,2.0,8.0,0,0,0
96,17/04/2017,18,4.0,6.0,13.0,0,0,0
97,18/04/2017,8,1.0,6.0,6.0,0,0,0
98,19/04/2017,27,9.0,13.0,24.0,0,0,0
99,20/04/2017,24,2.0,20.0,21.0,0,1,100
100,21/04/2017,36,8.0,16.0,33.0,0,0,0
101,22/04/2017,50,14.0,20.0,45.0,0,0,0
102,23/04/2017,8,3.0,5.0,7.0,0,0,0
103,24/04/2017,45,7.0,16.0,36.0,0,0,0
104,25/04/2017,21,4.0,14.0,18.0,0,0,0
105,26/04/2017,33,8.0,16.0,28.0,0,0,0
106,27/04/2017,19,2.0,11.0,14.0,0,0,0
107,28/04/2017,6,1.0,4.0,4.0,0,0,0
108,29/04/2017,9,2.0,4.0,5.0,0,0,0
109,30/04/2017,9,2.0,4.0,5.0,0,0,0

In [13]:
ds.describe()

,freeport,size,total,Total No. Cascade,protested,gsr encoding,weights
count,110.000000,109.000000,109.000000,109.000000,110.0,110.000000,110.000000
mean,66.463636,12.211009,23.834862,61.229358,0.0,0.281818,28.181818
std,155.503484,34.975937,47.588809,147.592133,0.0,0.743557,74.355726
min,1.000000,1.000000,1.000000,1.000000,0.0,0.000000,0.000000
25%,9.000000,2.000000,5.000000,6.000000,0.0,0.000000,0.000000
50%,22.000000,4.000000,10.000000,18.000000,0.0,0.000000,0.000000
75%,38.750000,10.000000,20.000000,34.000000,0.0,0.000000,0.000000
max,1033.000000,336.000000,296.000000,1002.000000,0.0,4.000000,400.000000

In [16]:
ds["size"]

0       1.0
1       1.0
2      11.0
3      11.0
4       1.0
5       1.0
6      12.0
7      10.0
8       6.0
9       1.0
10     10.0
11     11.0
12      1.0
13      4.0
14      2.0
15      1.0
16      1.0
17      1.0
18      5.0
19      4.0
20      1.0
21      1.0
22      7.0
23      NaN
24      3.0
25      1.0
26      1.0
27      2.0
28      1.0
29      2.0
       ...
80     13.0
81      9.0
82      2.0
83      7.0
84      3.0
85      7.0
86      5.0
87     14.0
88     12.0
89      4.0
90      3.0
91      3.0
92      2.0
93      2.0
94      1.0
95      7.0
96      4.0
97      1.0
98      9.0
99      2.0
100     8.0
101    14.0
102     3.0
103     7.0
104     4.0
105     8.0
106     2.0
107     1.0
108     2.0
109     2.0
Name: size, dtype: float64

In [63]:
import matplotlib.pyplot as plt
#fig, ax = plt.subplots()
#plt.figure( figsize=(20, 20), dpi=1000)
#ax.set_xticklabels(ds['Date'], fontsize=6)
lb =ds.plot(kind= 'line')
lb.show()
#plot.show()

AttributeError: 'AxesSubplot' object has no attribute 'show'